apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: kelseyhightower/kube-cert-manager:0.5.0
          args:
            - "-data-dir=/var/lib/cert-manager"
            # - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
            #  if net is working (we can uncomment); 
            #    get valit certificate from encrypt which 
            #    my browser trusts and inject as kubernetes secret on the 
            #    backend co that my pod doesn't know the different
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
            - "sync-interval=30"
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
        - name: kubectl
          image: kelseyhightower/kubectl:1.4.0
          args:
            - "proxy"
      volumes:
        - name: "data"
          gcePersistentDisk:
            pdName: kube-cert-manager
            fstype: ext4

