apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: lobsters
  name: lobsters
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lobsters
    spec:
      containers:
        - name: lobsters
          image: kelseyhightower/lobsters:2.0.0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: database-url
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 0.5
              memory: 200M
            limits:
              cpu: 0.5
              memory: 200M
