apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
      name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: mysql-password
            - name: MYSQL_USER
              value: lobsters
            - name: MYSQL_DATABASE
              value: lobsters
          ports:
            - name: mysql
              containerPort: 3306
          resources:
            requests:
              cpu: 1
              memory: 4
            limits:
              cpu: 1
              memory: 4
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      volumes:
        - name: "mysql"
          persistentVolumeClaim:
            claimName: mysql
          #gcePersistentDisk:
          #  pdName: mysql
          #  fstype: ext4
