apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: lobsters-db-schema-load
spec:
  selector:
    matchLabels:
      task: db-schema-load
  template:
    metadata:
      name: lobsters-db-schema-load
      labels:
        task: db-schema-load
    spec:
      containers:
        - name: lobsters
          image: kelseyhightower/lobsters:testing
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: database-url
          command:
            - "/usr/local/bundle/bin/rake"
            - "db:schema:load"
          resources:
            requests:
              cpu: 0.5
              memory: 100M
            limits:
              cpu: 0.5
              memory: 200M
      restartPolicy: Never
